# Generated by Django 4.1.5 on 2023-01-15 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disclose', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pet_pictures')),
                ('petname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('P', 'Para adoção'), ('A', 'Adotado')], max_length=1)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disclose.breed')),
                ('tags', models.ManyToManyField(to='disclose.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
