# Generated by Django 4.1.5 on 2023-01-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclose', '0005_alter_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(default='default-picture.jpg', upload_to='pet_pictures'),
        ),
    ]
